### ISSUE TITLE
Can this module manage several ell motors connected to an extension board?

### ISSUE THREAD

**Issue by ejetzer** [augvislab/elliptec_stage#1]
I have three motors that I would like to control from one extension control board; can this module already do it? If not, I am interested in adding the functionnality and will fork.

**Comment by YutaItoh** [comment]
hi @ejetzer, Thanks for checking our code.
If I remember correctly, our motor class only assumes one motor.

Internally, the motor class just sends a proper serial command with the default device id specified (i.e., 0 is added in a serial code-compose function).
Since the official protocol itself does support motor selection, I would modify the class so that the user embed the device address when generating a motor class instance. 
https://www.thorlabs.co.jp/Software/Elliptec/Communications_Protocol/ELLx%20modules%20protocol%20manual.pdf

Hope this helps.
